/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.114
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for the Audition model.
 * @export
 * @interface Audition
 */
export interface Audition {
    /**
     * 
     * @type {number}
     * @memberof Audition
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Audition
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Audition
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Audition
     */
    readonly archiveAt: Date | null;
    /**
     * Name of the audition
     * @type {string}
     * @memberof Audition
     */
    name: string;
    /**
     * Description of the audition
     * @type {string}
     * @memberof Audition
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof Audition
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof Audition
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Audition
     */
    readonly updatedBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Audition
     */
    production: number;
    /**
     * Venue for the audition
     * @type {number}
     * @memberof Audition
     */
    venue?: number | null;
}

/**
 * Check if a given object implements the Audition interface.
 */
export function instanceOfAudition(value: object): value is Audition {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('production' in value) || value['production'] === undefined) return false;
    return true;
}

export function AuditionFromJSON(json: any): Audition {
    return AuditionFromJSONTyped(json, false);
}

export function AuditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Audition {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'name': json['name'],
        'description': json['description'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'production': json['production'],
        'venue': json['venue'] == null ? undefined : json['venue'],
    };
}

export function AuditionToJSON(json: any): Audition {
    return AuditionToJSONTyped(json, false);
}

export function AuditionToJSONTyped(value?: Omit<Audition, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'production': value['production'],
        'venue': value['venue'],
    };
}

