/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckboxConfig
 */
export interface CheckboxConfig {
    /**
     * Label for the checkbox
     * @type {string}
     * @memberof CheckboxConfig
     */
    label: string;
    /**
     * Whether the checkbox is checked by default
     * @type {boolean}
     * @memberof CheckboxConfig
     */
    isChecked?: boolean;
}

/**
 * Check if a given object implements the CheckboxConfig interface.
 */
export function instanceOfCheckboxConfig(value: object): value is CheckboxConfig {
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function CheckboxConfigFromJSON(json: any): CheckboxConfig {
    return CheckboxConfigFromJSONTyped(json, false);
}

export function CheckboxConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckboxConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'isChecked': json['is_checked'] == null ? undefined : json['is_checked'],
    };
}

export function CheckboxConfigToJSON(json: any): CheckboxConfig {
    return CheckboxConfigToJSONTyped(json, false);
}

export function CheckboxConfigToJSONTyped(value?: CheckboxConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'is_checked': value['isChecked'],
    };
}

