/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.94
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `new` - New
 * * `good` - Good
 * * `fair` - Fair
 * * `poor` - Poor
 * * `damaged` - Damaged
 * * `out_of_service` - Out of Service
 * @export
 */
export const ConditionEnum = {
    New: 'new',
    Good: 'good',
    Fair: 'fair',
    Poor: 'poor',
    Damaged: 'damaged',
    OutOfService: 'out_of_service'
} as const;
export type ConditionEnum = typeof ConditionEnum[keyof typeof ConditionEnum];


export function instanceOfConditionEnum(value: any): boolean {
    for (const key in ConditionEnum) {
        if (Object.prototype.hasOwnProperty.call(ConditionEnum, key)) {
            if (ConditionEnum[key as keyof typeof ConditionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ConditionEnumFromJSON(json: any): ConditionEnum {
    return ConditionEnumFromJSONTyped(json, false);
}

export function ConditionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConditionEnum {
    return json as ConditionEnum;
}

export function ConditionEnumToJSON(value?: ConditionEnum | null): any {
    return value as any;
}

export function ConditionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ConditionEnum {
    return value as ConditionEnum;
}

