/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `AUD` - AUD - Australian Dollar
 * * `CAD` - CAD - Canadian Dollar
 * * `EUR` - EUR - Euro
 * * `GBP` - GBP - British Pound
 * * `JPY` - JPY - Japanese Yen
 * * `NZD` - NZD - New Zealand Dollar
 * * `USD` - USD - United States Dollar
 * @export
 */
export const CurrencyEnum = {
    Aud: 'AUD',
    Cad: 'CAD',
    Eur: 'EUR',
    Gbp: 'GBP',
    Jpy: 'JPY',
    Nzd: 'NZD',
    Usd: 'USD'
} as const;
export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];


export function instanceOfCurrencyEnum(value: any): boolean {
    for (const key in CurrencyEnum) {
        if (Object.prototype.hasOwnProperty.call(CurrencyEnum, key)) {
            if (CurrencyEnum[key as keyof typeof CurrencyEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CurrencyEnumFromJSON(json: any): CurrencyEnum {
    return CurrencyEnumFromJSONTyped(json, false);
}

export function CurrencyEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyEnum {
    return json as CurrencyEnum;
}

export function CurrencyEnumToJSON(value?: CurrencyEnum | null): any {
    return value as any;
}

export function CurrencyEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): CurrencyEnum {
    return value as CurrencyEnum;
}

