/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.110
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DatetimeConfig
 */
export interface DatetimeConfig {
    /**
     * 
     * @type {Date}
     * @memberof DatetimeConfig
     */
    minDatetime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof DatetimeConfig
     */
    maxDatetime?: Date | null;
}

/**
 * Check if a given object implements the DatetimeConfig interface.
 */
export function instanceOfDatetimeConfig(value: object): value is DatetimeConfig {
    return true;
}

export function DatetimeConfigFromJSON(json: any): DatetimeConfig {
    return DatetimeConfigFromJSONTyped(json, false);
}

export function DatetimeConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): DatetimeConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'minDatetime': json['min_datetime'] == null ? undefined : (new Date(json['min_datetime'])),
        'maxDatetime': json['max_datetime'] == null ? undefined : (new Date(json['max_datetime'])),
    };
}

export function DatetimeConfigToJSON(json: any): DatetimeConfig {
    return DatetimeConfigToJSONTyped(json, false);
}

export function DatetimeConfigToJSONTyped(value?: DatetimeConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_datetime': value['minDatetime'] === null ? null : ((value['minDatetime'] as any)?.toISOString()),
        'max_datetime': value['maxDatetime'] === null ? null : ((value['maxDatetime'] as any)?.toISOString()),
    };
}

