/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.103
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentVersion
 */
export interface DocumentVersion {
    /**
     * 
     * @type {number}
     * @memberof DocumentVersion
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof DocumentVersion
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentVersion
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentVersion
     */
    readonly archiveAt: Date | null;
    /**
     * The version of the document
     * @type {number}
     * @memberof DocumentVersion
     */
    readonly version: number;
    /**
     * URL to the document file
     * @type {string}
     * @memberof DocumentVersion
     */
    fileUrl: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentVersion
     */
    versionNotes?: string;
    /**
     * 
     * @type {number}
     * @memberof DocumentVersion
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentVersion
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentVersion
     */
    readonly updatedBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentVersion
     */
    document: number;
}

/**
 * Check if a given object implements the DocumentVersion interface.
 */
export function instanceOfDocumentVersion(value: object): value is DocumentVersion {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('fileUrl' in value) || value['fileUrl'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('document' in value) || value['document'] === undefined) return false;
    return true;
}

export function DocumentVersionFromJSON(json: any): DocumentVersion {
    return DocumentVersionFromJSONTyped(json, false);
}

export function DocumentVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'version': json['version'],
        'fileUrl': json['file_url'],
        'versionNotes': json['version_notes'] == null ? undefined : json['version_notes'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'document': json['document'],
    };
}

export function DocumentVersionToJSON(json: any): DocumentVersion {
    return DocumentVersionToJSONTyped(json, false);
}

export function DocumentVersionToJSONTyped(value?: Omit<DocumentVersion, 'id'|'created_at'|'updated_at'|'archive_at'|'version'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_url': value['fileUrl'],
        'version_notes': value['versionNotes'],
        'document': value['document'],
    };
}

