/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.73
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Tag } from './Tag';
import {
    TagFromJSON,
    TagFromJSONTyped,
    TagToJSON,
    TagToJSONTyped,
} from './Tag';
import type { Document } from './Document';
import {
    DocumentFromJSON,
    DocumentFromJSONTyped,
    DocumentToJSON,
    DocumentToJSONTyped,
} from './Document';

/**
 * 
 * @export
 * @interface DocumentTag
 */
export interface DocumentTag {
    /**
     * 
     * @type {number}
     * @memberof DocumentTag
     */
    readonly id: number;
    /**
     * 
     * @type {Tag}
     * @memberof DocumentTag
     */
    readonly tag: Tag;
    /**
     * 
     * @type {Document}
     * @memberof DocumentTag
     */
    readonly document: Document;
    /**
     * 
     * @type {Date}
     * @memberof DocumentTag
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentTag
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof DocumentTag
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentTag
     */
    tenant: number;
    /**
     * 
     * @type {number}
     * @memberof DocumentTag
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof DocumentTag
     */
    updatedBy?: number | null;
}

/**
 * Check if a given object implements the DocumentTag interface.
 */
export function instanceOfDocumentTag(value: object): value is DocumentTag {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('tag' in value) || value['tag'] === undefined) return false;
    if (!('document' in value) || value['document'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function DocumentTagFromJSON(json: any): DocumentTag {
    return DocumentTagFromJSONTyped(json, false);
}

export function DocumentTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentTag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'tag': TagFromJSON(json['tag']),
        'document': DocumentFromJSON(json['document']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function DocumentTagToJSON(json: any): DocumentTag {
    return DocumentTagToJSONTyped(json, false);
}

export function DocumentTagToJSONTyped(value?: Omit<DocumentTag, 'id'|'tag'|'document'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
    };
}

