/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.62
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Folder
 */
export interface Folder {
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Folder
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Folder
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Folder
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Folder
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    tenant: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    repo: number;
    /**
     * 
     * @type {number}
     * @memberof Folder
     */
    parent?: number | null;
}

/**
 * Check if a given object implements the Folder interface.
 */
export function instanceOfFolder(value: object): value is Folder {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('repo' in value) || value['repo'] === undefined) return false;
    return true;
}

export function FolderFromJSON(json: any): Folder {
    return FolderFromJSONTyped(json, false);
}

export function FolderFromJSONTyped(json: any, ignoreDiscriminator: boolean): Folder {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'repo': json['repo'],
        'parent': json['parent'] == null ? undefined : json['parent'],
    };
}

export function FolderToJSON(json: any): Folder {
    return FolderToJSONTyped(json, false);
}

export function FolderToJSONTyped(value?: Omit<Folder, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'repo': value['repo'],
        'parent': value['parent'],
    };
}

