/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.62
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Form
 */
export interface Form {
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Form
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Form
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Form
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof Form
     */
    openDateTime?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Form
     */
    closeDateTime?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    maxSubmissions?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    maxIndividualSubmissions?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Form
     */
    successMessage?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Form
     */
    isTemplate?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Form
     */
    isActive?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    tenant: number;
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Form
     */
    updatedBy?: number | null;
    /**
     * If this form is associated with a production, select it here.
     * @type {number}
     * @memberof Form
     */
    production?: number | null;
}

/**
 * Check if a given object implements the Form interface.
 */
export function instanceOfForm(value: object): value is Form {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function FormFromJSON(json: any): Form {
    return FormFromJSONTyped(json, false);
}

export function FormFromJSONTyped(json: any, ignoreDiscriminator: boolean): Form {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'title': json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'openDateTime': json['open_date_time'] == null ? undefined : (new Date(json['open_date_time'])),
        'closeDateTime': json['close_date_time'] == null ? undefined : (new Date(json['close_date_time'])),
        'maxSubmissions': json['max_submissions'] == null ? undefined : json['max_submissions'],
        'maxIndividualSubmissions': json['max_individual_submissions'] == null ? undefined : json['max_individual_submissions'],
        'successMessage': json['success_message'] == null ? undefined : json['success_message'],
        'isTemplate': json['is_template'] == null ? undefined : json['is_template'],
        'isActive': json['is_active'] == null ? undefined : json['is_active'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'production': json['production'] == null ? undefined : json['production'],
    };
}

export function FormToJSON(json: any): Form {
    return FormToJSONTyped(json, false);
}

export function FormToJSONTyped(value?: Omit<Form, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'title': value['title'],
        'description': value['description'],
        'open_date_time': value['openDateTime'] === null ? null : ((value['openDateTime'] as any)?.toISOString()),
        'close_date_time': value['closeDateTime'] === null ? null : ((value['closeDateTime'] as any)?.toISOString()),
        'max_submissions': value['maxSubmissions'],
        'max_individual_submissions': value['maxIndividualSubmissions'],
        'success_message': value['successMessage'],
        'is_template': value['isTemplate'],
        'is_active': value['isActive'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'production': value['production'],
    };
}

