/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.97
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultipleChoiceConfiguration
 */
export interface MultipleChoiceConfiguration {
    /**
     * List of options for the multiple choice field
     * @type {Array<string>}
     * @memberof MultipleChoiceConfiguration
     */
    options: Array<string>;
    /**
     * Whether multiple selections are allowed
     * @type {boolean}
     * @memberof MultipleChoiceConfiguration
     */
    allowMultiple?: boolean;
    /**
     * Whether an 'Other' option is allowed for custom input
     * @type {boolean}
     * @memberof MultipleChoiceConfiguration
     */
    allowOther?: boolean;
    /**
     * 
     * @type {string}
     * @memberof MultipleChoiceConfiguration
     */
    otherPlaceholder?: string | null;
}

/**
 * Check if a given object implements the MultipleChoiceConfiguration interface.
 */
export function instanceOfMultipleChoiceConfiguration(value: object): value is MultipleChoiceConfiguration {
    if (!('options' in value) || value['options'] === undefined) return false;
    return true;
}

export function MultipleChoiceConfigurationFromJSON(json: any): MultipleChoiceConfiguration {
    return MultipleChoiceConfigurationFromJSONTyped(json, false);
}

export function MultipleChoiceConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultipleChoiceConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'options': json['options'],
        'allowMultiple': json['allow_multiple'] == null ? undefined : json['allow_multiple'],
        'allowOther': json['allow_other'] == null ? undefined : json['allow_other'],
        'otherPlaceholder': json['other_placeholder'] == null ? undefined : json['other_placeholder'],
    };
}

export function MultipleChoiceConfigurationToJSON(json: any): MultipleChoiceConfiguration {
    return MultipleChoiceConfigurationToJSONTyped(json, false);
}

export function MultipleChoiceConfigurationToJSONTyped(value?: MultipleChoiceConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'options': value['options'],
        'allow_multiple': value['allowMultiple'],
        'allow_other': value['allowOther'],
        'other_placeholder': value['otherPlaceholder'],
    };
}

