/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.110
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NumberConfig
 */
export interface NumberConfig {
    /**
     * 
     * @type {number}
     * @memberof NumberConfig
     */
    minValue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NumberConfig
     */
    maxValue?: number | null;
    /**
     * Step increment for the number input
     * @type {number}
     * @memberof NumberConfig
     */
    step?: number;
}

/**
 * Check if a given object implements the NumberConfig interface.
 */
export function instanceOfNumberConfig(value: object): value is NumberConfig {
    return true;
}

export function NumberConfigFromJSON(json: any): NumberConfig {
    return NumberConfigFromJSONTyped(json, false);
}

export function NumberConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): NumberConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'minValue': json['min_value'] == null ? undefined : json['min_value'],
        'maxValue': json['max_value'] == null ? undefined : json['max_value'],
        'step': json['step'] == null ? undefined : json['step'],
    };
}

export function NumberConfigToJSON(json: any): NumberConfig {
    return NumberConfigToJSONTyped(json, false);
}

export function NumberConfigToJSONTyped(value?: NumberConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_value': value['minValue'],
        'max_value': value['maxValue'],
        'step': value['step'],
    };
}

