/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';

/**
 * 
 * @export
 * @interface PaginatedVenueList
 */
export interface PaginatedVenueList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedVenueList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedVenueList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedVenueList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Venue>}
     * @memberof PaginatedVenueList
     */
    results: Array<Venue>;
}

/**
 * Check if a given object implements the PaginatedVenueList interface.
 */
export function instanceOfPaginatedVenueList(value: object): value is PaginatedVenueList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedVenueListFromJSON(json: any): PaginatedVenueList {
    return PaginatedVenueListFromJSONTyped(json, false);
}

export function PaginatedVenueListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedVenueList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(VenueFromJSON)),
    };
}

export function PaginatedVenueListToJSON(json: any): PaginatedVenueList {
    return PaginatedVenueListToJSONTyped(json, false);
}

export function PaginatedVenueListToJSONTyped(value?: PaginatedVenueList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(VenueToJSON)),
    };
}

