/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.114
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionBudgetSummary } from './ProductionBudgetSummary';
import {
    ProductionBudgetSummaryFromJSON,
    ProductionBudgetSummaryFromJSONTyped,
    ProductionBudgetSummaryToJSON,
    ProductionBudgetSummaryToJSONTyped,
} from './ProductionBudgetSummary';

/**
 * 
 * @export
 * @interface PaginatedProductionBudgetSummaryList
 */
export interface PaginatedProductionBudgetSummaryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ProductionBudgetSummary>}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    results: Array<ProductionBudgetSummary>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionBudgetSummaryList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedProductionBudgetSummaryList interface.
 */
export function instanceOfPaginatedProductionBudgetSummaryList(value: object): value is PaginatedProductionBudgetSummaryList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedProductionBudgetSummaryListFromJSON(json: any): PaginatedProductionBudgetSummaryList {
    return PaginatedProductionBudgetSummaryListFromJSONTyped(json, false);
}

export function PaginatedProductionBudgetSummaryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductionBudgetSummaryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductionBudgetSummaryFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedProductionBudgetSummaryListToJSON(json: any): PaginatedProductionBudgetSummaryList {
    return PaginatedProductionBudgetSummaryListToJSONTyped(json, false);
}

export function PaginatedProductionBudgetSummaryListToJSONTyped(value?: PaginatedProductionBudgetSummaryList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductionBudgetSummaryToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

