/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.97
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionIncomeCategory } from './ProductionIncomeCategory';
import {
    ProductionIncomeCategoryFromJSON,
    ProductionIncomeCategoryFromJSONTyped,
    ProductionIncomeCategoryToJSON,
    ProductionIncomeCategoryToJSONTyped,
} from './ProductionIncomeCategory';

/**
 * 
 * @export
 * @interface PaginatedProductionIncomeCategoryList
 */
export interface PaginatedProductionIncomeCategoryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ProductionIncomeCategory>}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    results: Array<ProductionIncomeCategory>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionIncomeCategoryList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedProductionIncomeCategoryList interface.
 */
export function instanceOfPaginatedProductionIncomeCategoryList(value: object): value is PaginatedProductionIncomeCategoryList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedProductionIncomeCategoryListFromJSON(json: any): PaginatedProductionIncomeCategoryList {
    return PaginatedProductionIncomeCategoryListFromJSONTyped(json, false);
}

export function PaginatedProductionIncomeCategoryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductionIncomeCategoryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductionIncomeCategoryFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedProductionIncomeCategoryListToJSON(json: any): PaginatedProductionIncomeCategoryList {
    return PaginatedProductionIncomeCategoryListToJSONTyped(json, false);
}

export function PaginatedProductionIncomeCategoryListToJSONTyped(value?: PaginatedProductionIncomeCategoryList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductionIncomeCategoryToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

