/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.111
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Expense } from './Expense';
import {
    ExpenseFromJSON,
    ExpenseFromJSONTyped,
    ExpenseToJSON,
    ExpenseToJSONTyped,
} from './Expense';

/**
 * 
 * @export
 * @interface PaginatedExpenseList
 */
export interface PaginatedExpenseList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedExpenseList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedExpenseList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedExpenseList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Expense>}
     * @memberof PaginatedExpenseList
     */
    results: Array<Expense>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedExpenseList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedExpenseList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedExpenseList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedExpenseList interface.
 */
export function instanceOfPaginatedExpenseList(value: object): value is PaginatedExpenseList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedExpenseListFromJSON(json: any): PaginatedExpenseList {
    return PaginatedExpenseListFromJSONTyped(json, false);
}

export function PaginatedExpenseListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedExpenseList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ExpenseFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedExpenseListToJSON(json: any): PaginatedExpenseList {
    return PaginatedExpenseListToJSONTyped(json, false);
}

export function PaginatedExpenseListToJSONTyped(value?: PaginatedExpenseList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ExpenseToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

