/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.41
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Production } from './Production';
import {
    ProductionFromJSON,
    ProductionFromJSONTyped,
    ProductionToJSON,
    ProductionToJSONTyped,
} from './Production';

/**
 * 
 * @export
 * @interface PaginatedProductionList
 */
export interface PaginatedProductionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Production>}
     * @memberof PaginatedProductionList
     */
    results: Array<Production>;
}

/**
 * Check if a given object implements the PaginatedProductionList interface.
 */
export function instanceOfPaginatedProductionList(value: object): value is PaginatedProductionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedProductionListFromJSON(json: any): PaginatedProductionList {
    return PaginatedProductionListFromJSONTyped(json, false);
}

export function PaginatedProductionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductionFromJSON)),
    };
}

export function PaginatedProductionListToJSON(json: any): PaginatedProductionList {
    return PaginatedProductionListToJSONTyped(json, false);
}

export function PaginatedProductionListToJSONTyped(value?: PaginatedProductionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductionToJSON)),
    };
}

