/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.94
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContextKey } from './ContextKey';
import {
    ContextKeyFromJSON,
    ContextKeyFromJSONTyped,
    ContextKeyToJSON,
    ContextKeyToJSONTyped,
} from './ContextKey';

/**
 * 
 * @export
 * @interface PaginatedContextKeyList
 */
export interface PaginatedContextKeyList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedContextKeyList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedContextKeyList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedContextKeyList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ContextKey>}
     * @memberof PaginatedContextKeyList
     */
    results: Array<ContextKey>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedContextKeyList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedContextKeyList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedContextKeyList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedContextKeyList interface.
 */
export function instanceOfPaginatedContextKeyList(value: object): value is PaginatedContextKeyList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedContextKeyListFromJSON(json: any): PaginatedContextKeyList {
    return PaginatedContextKeyListFromJSONTyped(json, false);
}

export function PaginatedContextKeyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedContextKeyList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ContextKeyFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedContextKeyListToJSON(json: any): PaginatedContextKeyList {
    return PaginatedContextKeyListToJSONTyped(json, false);
}

export function PaginatedContextKeyListToJSONTyped(value?: PaginatedContextKeyList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ContextKeyToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

