/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionCategoryAssignment } from './ProductionCategoryAssignment';
import {
    ProductionCategoryAssignmentFromJSON,
    ProductionCategoryAssignmentFromJSONTyped,
    ProductionCategoryAssignmentToJSON,
    ProductionCategoryAssignmentToJSONTyped,
} from './ProductionCategoryAssignment';

/**
 * 
 * @export
 * @interface PaginatedProductionCategoryAssignmentList
 */
export interface PaginatedProductionCategoryAssignmentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ProductionCategoryAssignment>}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    results: Array<ProductionCategoryAssignment>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionCategoryAssignmentList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedProductionCategoryAssignmentList interface.
 */
export function instanceOfPaginatedProductionCategoryAssignmentList(value: object): value is PaginatedProductionCategoryAssignmentList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedProductionCategoryAssignmentListFromJSON(json: any): PaginatedProductionCategoryAssignmentList {
    return PaginatedProductionCategoryAssignmentListFromJSONTyped(json, false);
}

export function PaginatedProductionCategoryAssignmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductionCategoryAssignmentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductionCategoryAssignmentFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedProductionCategoryAssignmentListToJSON(json: any): PaginatedProductionCategoryAssignmentList {
    return PaginatedProductionCategoryAssignmentListToJSONTyped(json, false);
}

export function PaginatedProductionCategoryAssignmentListToJSONTyped(value?: PaginatedProductionCategoryAssignmentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductionCategoryAssignmentToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

