/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Income } from './Income';
import {
    IncomeFromJSON,
    IncomeFromJSONTyped,
    IncomeToJSON,
    IncomeToJSONTyped,
} from './Income';

/**
 * 
 * @export
 * @interface PaginatedIncomeList
 */
export interface PaginatedIncomeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedIncomeList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedIncomeList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Income>}
     * @memberof PaginatedIncomeList
     */
    results: Array<Income>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedIncomeList interface.
 */
export function instanceOfPaginatedIncomeList(value: object): value is PaginatedIncomeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedIncomeListFromJSON(json: any): PaginatedIncomeList {
    return PaginatedIncomeListFromJSONTyped(json, false);
}

export function PaginatedIncomeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedIncomeList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(IncomeFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedIncomeListToJSON(json: any): PaginatedIncomeList {
    return PaginatedIncomeListToJSONTyped(json, false);
}

export function PaginatedIncomeListToJSONTyped(value?: PaginatedIncomeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(IncomeToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

