/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Reimbursement } from './Reimbursement';
import {
    ReimbursementFromJSON,
    ReimbursementFromJSONTyped,
    ReimbursementToJSON,
    ReimbursementToJSONTyped,
} from './Reimbursement';

/**
 * 
 * @export
 * @interface PaginatedReimbursementList
 */
export interface PaginatedReimbursementList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedReimbursementList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReimbursementList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedReimbursementList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Reimbursement>}
     * @memberof PaginatedReimbursementList
     */
    results: Array<Reimbursement>;
}

/**
 * Check if a given object implements the PaginatedReimbursementList interface.
 */
export function instanceOfPaginatedReimbursementList(value: object): value is PaginatedReimbursementList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedReimbursementListFromJSON(json: any): PaginatedReimbursementList {
    return PaginatedReimbursementListFromJSONTyped(json, false);
}

export function PaginatedReimbursementListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedReimbursementList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ReimbursementFromJSON)),
    };
}

export function PaginatedReimbursementListToJSON(json: any): PaginatedReimbursementList {
    return PaginatedReimbursementListToJSONTyped(json, false);
}

export function PaginatedReimbursementListToJSONTyped(value?: PaginatedReimbursementList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ReimbursementToJSON)),
    };
}

