/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.77
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Assignment } from './Assignment';
import {
    AssignmentFromJSON,
    AssignmentFromJSONTyped,
    AssignmentToJSON,
    AssignmentToJSONTyped,
} from './Assignment';

/**
 * 
 * @export
 * @interface PaginatedAssignmentList
 */
export interface PaginatedAssignmentList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAssignmentList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAssignmentList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAssignmentList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Assignment>}
     * @memberof PaginatedAssignmentList
     */
    results: Array<Assignment>;
}

/**
 * Check if a given object implements the PaginatedAssignmentList interface.
 */
export function instanceOfPaginatedAssignmentList(value: object): value is PaginatedAssignmentList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAssignmentListFromJSON(json: any): PaginatedAssignmentList {
    return PaginatedAssignmentListFromJSONTyped(json, false);
}

export function PaginatedAssignmentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAssignmentList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AssignmentFromJSON)),
    };
}

export function PaginatedAssignmentListToJSON(json: any): PaginatedAssignmentList {
    return PaginatedAssignmentListToJSONTyped(json, false);
}

export function PaginatedAssignmentListToJSONTyped(value?: PaginatedAssignmentList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AssignmentToJSON)),
    };
}

