/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IncomeCategory } from './IncomeCategory';
import {
    IncomeCategoryFromJSON,
    IncomeCategoryFromJSONTyped,
    IncomeCategoryToJSON,
    IncomeCategoryToJSONTyped,
} from './IncomeCategory';

/**
 * 
 * @export
 * @interface PaginatedIncomeCategoryList
 */
export interface PaginatedIncomeCategoryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeCategoryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedIncomeCategoryList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedIncomeCategoryList
     */
    previous?: string;
    /**
     * 
     * @type {Array<IncomeCategory>}
     * @memberof PaginatedIncomeCategoryList
     */
    results: Array<IncomeCategory>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeCategoryList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeCategoryList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedIncomeCategoryList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedIncomeCategoryList interface.
 */
export function instanceOfPaginatedIncomeCategoryList(value: object): value is PaginatedIncomeCategoryList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedIncomeCategoryListFromJSON(json: any): PaginatedIncomeCategoryList {
    return PaginatedIncomeCategoryListFromJSONTyped(json, false);
}

export function PaginatedIncomeCategoryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedIncomeCategoryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(IncomeCategoryFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedIncomeCategoryListToJSON(json: any): PaginatedIncomeCategoryList {
    return PaginatedIncomeCategoryListToJSONTyped(json, false);
}

export function PaginatedIncomeCategoryListToJSONTyped(value?: PaginatedIncomeCategoryList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(IncomeCategoryToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

