/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.71
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionMember } from './ProductionMember';
import {
    ProductionMemberFromJSON,
    ProductionMemberFromJSONTyped,
    ProductionMemberToJSON,
    ProductionMemberToJSONTyped,
} from './ProductionMember';

/**
 * 
 * @export
 * @interface PaginatedProductionMemberList
 */
export interface PaginatedProductionMemberList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedProductionMemberList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionMemberList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedProductionMemberList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ProductionMember>}
     * @memberof PaginatedProductionMemberList
     */
    results: Array<ProductionMember>;
}

/**
 * Check if a given object implements the PaginatedProductionMemberList interface.
 */
export function instanceOfPaginatedProductionMemberList(value: object): value is PaginatedProductionMemberList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedProductionMemberListFromJSON(json: any): PaginatedProductionMemberList {
    return PaginatedProductionMemberListFromJSONTyped(json, false);
}

export function PaginatedProductionMemberListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedProductionMemberList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(ProductionMemberFromJSON)),
    };
}

export function PaginatedProductionMemberListToJSON(json: any): PaginatedProductionMemberList {
    return PaginatedProductionMemberListToJSONTyped(json, false);
}

export function PaginatedProductionMemberListToJSONTyped(value?: PaginatedProductionMemberList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(ProductionMemberToJSON)),
    };
}

