/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.89
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Signup } from './Signup';
import {
    SignupFromJSON,
    SignupFromJSONTyped,
    SignupToJSON,
    SignupToJSONTyped,
} from './Signup';

/**
 * 
 * @export
 * @interface PaginatedSignupList
 */
export interface PaginatedSignupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSignupList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSignupList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSignupList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Signup>}
     * @memberof PaginatedSignupList
     */
    results: Array<Signup>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedSignupList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedSignupList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedSignupList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedSignupList interface.
 */
export function instanceOfPaginatedSignupList(value: object): value is PaginatedSignupList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSignupListFromJSON(json: any): PaginatedSignupList {
    return PaginatedSignupListFromJSONTyped(json, false);
}

export function PaginatedSignupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSignupList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SignupFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedSignupListToJSON(json: any): PaginatedSignupList {
    return PaginatedSignupListToJSONTyped(json, false);
}

export function PaginatedSignupListToJSONTyped(value?: PaginatedSignupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SignupToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

