/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.89
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Audition } from './Audition';
import {
    AuditionFromJSON,
    AuditionFromJSONTyped,
    AuditionToJSON,
    AuditionToJSONTyped,
} from './Audition';

/**
 * 
 * @export
 * @interface PaginatedAuditionList
 */
export interface PaginatedAuditionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditionList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditionList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Audition>}
     * @memberof PaginatedAuditionList
     */
    results: Array<Audition>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditionList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditionList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditionList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedAuditionList interface.
 */
export function instanceOfPaginatedAuditionList(value: object): value is PaginatedAuditionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAuditionListFromJSON(json: any): PaginatedAuditionList {
    return PaginatedAuditionListFromJSONTyped(json, false);
}

export function PaginatedAuditionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAuditionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AuditionFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedAuditionListToJSON(json: any): PaginatedAuditionList {
    return PaginatedAuditionListToJSONTyped(json, false);
}

export function PaginatedAuditionListToJSONTyped(value?: PaginatedAuditionList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AuditionToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

