/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketType } from './TicketType';
import {
    TicketTypeFromJSON,
    TicketTypeFromJSONTyped,
    TicketTypeToJSON,
    TicketTypeToJSONTyped,
} from './TicketType';

/**
 * 
 * @export
 * @interface PaginatedTicketTypeList
 */
export interface PaginatedTicketTypeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketTypeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTicketTypeList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTicketTypeList
     */
    previous?: string;
    /**
     * 
     * @type {Array<TicketType>}
     * @memberof PaginatedTicketTypeList
     */
    results: Array<TicketType>;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketTypeList
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketTypeList
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedTicketTypeList
     */
    pageCount?: number;
}

/**
 * Check if a given object implements the PaginatedTicketTypeList interface.
 */
export function instanceOfPaginatedTicketTypeList(value: object): value is PaginatedTicketTypeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTicketTypeListFromJSON(json: any): PaginatedTicketTypeList {
    return PaginatedTicketTypeListFromJSONTyped(json, false);
}

export function PaginatedTicketTypeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTicketTypeList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TicketTypeFromJSON)),
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'pageCount': json['page_count'] == null ? undefined : json['page_count'],
    };
}

export function PaginatedTicketTypeListToJSON(json: any): PaginatedTicketTypeList {
    return PaginatedTicketTypeListToJSONTyped(json, false);
}

export function PaginatedTicketTypeListToJSONTyped(value?: PaginatedTicketTypeList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TicketTypeToJSON)),
        'page': value['page'],
        'page_size': value['pageSize'],
        'page_count': value['pageCount'],
    };
}

