/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.46
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedEmploymentType
 */
export interface PatchedEmploymentType {
    /**
     * 
     * @type {number}
     * @memberof PatchedEmploymentType
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmploymentType
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmploymentType
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedEmploymentType
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmploymentType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedEmploymentType
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedEmploymentType
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedEmploymentType
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedEmploymentType
     */
    updatedBy?: number | null;
}

/**
 * Check if a given object implements the PatchedEmploymentType interface.
 */
export function instanceOfPatchedEmploymentType(value: object): value is PatchedEmploymentType {
    return true;
}

export function PatchedEmploymentTypeFromJSON(json: any): PatchedEmploymentType {
    return PatchedEmploymentTypeFromJSONTyped(json, false);
}

export function PatchedEmploymentTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedEmploymentType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function PatchedEmploymentTypeToJSON(json: any): PatchedEmploymentType {
    return PatchedEmploymentTypeToJSONTyped(json, false);
}

export function PatchedEmploymentTypeToJSONTyped(value?: Omit<PatchedEmploymentType, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'description': value['description'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
    };
}

