/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedRehearsal
 */
export interface PatchedRehearsal {
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRehearsal
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRehearsal
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRehearsal
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRehearsal
     */
    startDatetime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedRehearsal
     */
    endDatetime?: Date;
    /**
     * Rehearsal Notes, e.g. what scene are being rehearsed, what is needed, etc. Support Markdown formatting.
     * @type {string}
     * @memberof PatchedRehearsal
     */
    notes?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    production?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedRehearsal
     */
    venue?: number | null;
}

/**
 * Check if a given object implements the PatchedRehearsal interface.
 */
export function instanceOfPatchedRehearsal(value: object): value is PatchedRehearsal {
    return true;
}

export function PatchedRehearsalFromJSON(json: any): PatchedRehearsal {
    return PatchedRehearsalFromJSONTyped(json, false);
}

export function PatchedRehearsalFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRehearsal {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'startDatetime': json['start_datetime'] == null ? undefined : (new Date(json['start_datetime'])),
        'endDatetime': json['end_datetime'] == null ? undefined : (new Date(json['end_datetime'])),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'production': json['production'] == null ? undefined : json['production'],
        'venue': json['venue'] == null ? undefined : json['venue'],
    };
}

export function PatchedRehearsalToJSON(json: any): PatchedRehearsal {
    return PatchedRehearsalToJSONTyped(json, false);
}

export function PatchedRehearsalToJSONTyped(value?: Omit<PatchedRehearsal, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'start_datetime': value['startDatetime'] == null ? undefined : ((value['startDatetime']).toISOString()),
        'end_datetime': value['endDatetime'] == null ? undefined : ((value['endDatetime']).toISOString()),
        'notes': value['notes'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'production': value['production'],
        'venue': value['venue'],
    };
}

