/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.93
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TicketStatusEnum } from './TicketStatusEnum';
import {
    TicketStatusEnumFromJSON,
    TicketStatusEnumFromJSONTyped,
    TicketStatusEnumToJSON,
    TicketStatusEnumToJSONTyped,
} from './TicketStatusEnum';
import type { Purchase } from './Purchase';
import {
    PurchaseFromJSON,
    PurchaseFromJSONTyped,
    PurchaseToJSON,
    PurchaseToJSONTyped,
} from './Purchase';
import type { SectionSeat } from './SectionSeat';
import {
    SectionSeatFromJSON,
    SectionSeatFromJSONTyped,
    SectionSeatToJSON,
    SectionSeatToJSONTyped,
} from './SectionSeat';
import type { TicketType } from './TicketType';
import {
    TicketTypeFromJSON,
    TicketTypeFromJSONTyped,
    TicketTypeToJSON,
    TicketTypeToJSONTyped,
} from './TicketType';

/**
 * 
 * @export
 * @interface PatchedTicket
 */
export interface PatchedTicket {
    /**
     * 
     * @type {number}
     * @memberof PatchedTicket
     */
    readonly id?: number;
    /**
     * 
     * @type {SectionSeat}
     * @memberof PatchedTicket
     */
    readonly sectionSeat?: SectionSeat;
    /**
     * 
     * @type {TicketType}
     * @memberof PatchedTicket
     */
    readonly ticketType?: TicketType;
    /**
     * 
     * @type {Purchase}
     * @memberof PatchedTicket
     */
    readonly purchase?: Purchase;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicket
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicket
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicket
     */
    readonly archiveAt?: Date | null;
    /**
     * Unique identifier for the ticket, used for tracking and validation.
     * @type {string}
     * @memberof PatchedTicket
     */
    readonly ticketUuid?: string;
    /**
     * Current status of the ticket.
     * 
     * * `active` - Active
     * * `used` - Used
     * * `refunded` - Refunded
     * * `cancelled` - Cancelled
     * * `transferred` - Transferred
     * @type {TicketStatusEnum}
     * @memberof PatchedTicket
     */
    status?: TicketStatusEnum;
    /**
     * Price of the ticket at the time of purchase.
     * @type {string}
     * @memberof PatchedTicket
     */
    price?: string;
    /**
     * Timestamp when the ticket was checked in. Null if not checked in.
     * @type {Date}
     * @memberof PatchedTicket
     */
    checkedInAt?: Date | null;
    /**
     * Alias used by the user who checked in the ticket. Useful for tracking check-ins by staff or volunteers who may not have a user account, or integrations which use a system account.
     * @type {string}
     * @memberof PatchedTicket
     */
    checkedInByAlias?: string;
    /**
     * Location where the ticket was checked in. Useful for tracking check-ins at different points of entry or systems.
     * @type {string}
     * @memberof PatchedTicket
     */
    checkedInLocation?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicket
     */
    readonly tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicket
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicket
     */
    readonly updatedBy?: number | null;
    /**
     * The performance for which this ticket is valid.
     * @type {number}
     * @memberof PatchedTicket
     */
    performance?: number;
    /**
     * The section for this ticket
     * @type {number}
     * @memberof PatchedTicket
     */
    section?: number;
    /**
     * The specific seat for this ticket.
     * @type {number}
     * @memberof PatchedTicket
     */
    seat?: number | null;
    /**
     * User who checked in the ticket. Null if not checked in.
     * @type {number}
     * @memberof PatchedTicket
     */
    checkedInByUser?: number | null;
}



/**
 * Check if a given object implements the PatchedTicket interface.
 */
export function instanceOfPatchedTicket(value: object): value is PatchedTicket {
    return true;
}

export function PatchedTicketFromJSON(json: any): PatchedTicket {
    return PatchedTicketFromJSONTyped(json, false);
}

export function PatchedTicketFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTicket {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'sectionSeat': json['section_seat'] == null ? undefined : SectionSeatFromJSON(json['section_seat']),
        'ticketType': json['ticket_type'] == null ? undefined : TicketTypeFromJSON(json['ticket_type']),
        'purchase': json['purchase'] == null ? undefined : PurchaseFromJSON(json['purchase']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'ticketUuid': json['ticket_uuid'] == null ? undefined : json['ticket_uuid'],
        'status': json['status'] == null ? undefined : TicketStatusEnumFromJSON(json['status']),
        'price': json['price'] == null ? undefined : json['price'],
        'checkedInAt': json['checked_in_at'] == null ? undefined : (new Date(json['checked_in_at'])),
        'checkedInByAlias': json['checked_in_by_alias'] == null ? undefined : json['checked_in_by_alias'],
        'checkedInLocation': json['checked_in_location'] == null ? undefined : json['checked_in_location'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'performance': json['performance'] == null ? undefined : json['performance'],
        'section': json['section'] == null ? undefined : json['section'],
        'seat': json['seat'] == null ? undefined : json['seat'],
        'checkedInByUser': json['checked_in_by_user'] == null ? undefined : json['checked_in_by_user'],
    };
}

export function PatchedTicketToJSON(json: any): PatchedTicket {
    return PatchedTicketToJSONTyped(json, false);
}

export function PatchedTicketToJSONTyped(value?: Omit<PatchedTicket, 'id'|'section_seat'|'ticket_type'|'purchase'|'created_at'|'updated_at'|'archive_at'|'ticket_uuid'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': TicketStatusEnumToJSON(value['status']),
        'price': value['price'],
        'checked_in_at': value['checkedInAt'] === null ? null : ((value['checkedInAt'] as any)?.toISOString()),
        'checked_in_by_alias': value['checkedInByAlias'],
        'checked_in_location': value['checkedInLocation'],
        'performance': value['performance'],
        'section': value['section'],
        'seat': value['seat'],
        'checked_in_by_user': value['checkedInByUser'],
    };
}

