/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedContext
 */
export interface PatchedContext {
    /**
     * 
     * @type {number}
     * @memberof PatchedContext
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedContext
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedContext
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedContext
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedContext
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedContext
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedContext
     */
    createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedContext
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedContext
     */
    key?: number;
}

/**
 * Check if a given object implements the PatchedContext interface.
 */
export function instanceOfPatchedContext(value: object): value is PatchedContext {
    return true;
}

export function PatchedContextFromJSON(json: any): PatchedContext {
    return PatchedContextFromJSONTyped(json, false);
}

export function PatchedContextFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedContext {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'value': json['value'] == null ? undefined : json['value'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'key': json['key'] == null ? undefined : json['key'],
    };
}

export function PatchedContextToJSON(json: any): PatchedContext {
    return PatchedContextToJSONTyped(json, false);
}

export function PatchedContextToJSONTyped(value?: Omit<PatchedContext, 'id'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'value': value['value'],
        'tenant': value['tenant'],
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'key': value['key'],
    };
}

