/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.74
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedCostCategory
 */
export interface PatchedCostCategory {
    /**
     * 
     * @type {number}
     * @memberof PatchedCostCategory
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCostCategory
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCostCategory
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedCostCategory
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedCostCategory
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCostCategory
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCostCategory
     */
    lineCode?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedCostCategory
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedCostCategory
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedCostCategory
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedCostCategory
     */
    parent?: number | null;
}

/**
 * Check if a given object implements the PatchedCostCategory interface.
 */
export function instanceOfPatchedCostCategory(value: object): value is PatchedCostCategory {
    return true;
}

export function PatchedCostCategoryFromJSON(json: any): PatchedCostCategory {
    return PatchedCostCategoryFromJSONTyped(json, false);
}

export function PatchedCostCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCostCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'lineCode': json['line_code'] == null ? undefined : json['line_code'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'parent': json['parent'] == null ? undefined : json['parent'],
    };
}

export function PatchedCostCategoryToJSON(json: any): PatchedCostCategory {
    return PatchedCostCategoryToJSONTyped(json, false);
}

export function PatchedCostCategoryToJSONTyped(value?: Omit<PatchedCostCategory, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'description': value['description'],
        'line_code': value['lineCode'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'parent': value['parent'],
    };
}

