/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.74
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentStatusEnum } from './DocumentStatusEnum';
import {
    DocumentStatusEnumFromJSON,
    DocumentStatusEnumFromJSONTyped,
    DocumentStatusEnumToJSON,
    DocumentStatusEnumToJSONTyped,
} from './DocumentStatusEnum';

/**
 * 
 * @export
 * @interface PatchedDocument
 */
export interface PatchedDocument {
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDocument
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDocument
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedDocument
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedDocument
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedDocument
     */
    description?: string;
    /**
     * 
     * @type {DocumentStatusEnum}
     * @memberof PatchedDocument
     */
    status?: DocumentStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    production?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    author?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    repo?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedDocument
     */
    folder?: number | null;
    /**
     * The document that supersedes this one, if any
     * @type {number}
     * @memberof PatchedDocument
     */
    supersededBy?: number | null;
    /**
     * 
     * @type {Array<number>}
     * @memberof PatchedDocument
     */
    tags?: Array<number>;
}



/**
 * Check if a given object implements the PatchedDocument interface.
 */
export function instanceOfPatchedDocument(value: object): value is PatchedDocument {
    return true;
}

export function PatchedDocumentFromJSON(json: any): PatchedDocument {
    return PatchedDocumentFromJSONTyped(json, false);
}

export function PatchedDocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedDocument {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'status': json['status'] == null ? undefined : DocumentStatusEnumFromJSON(json['status']),
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'production': json['production'] == null ? undefined : json['production'],
        'author': json['author'] == null ? undefined : json['author'],
        'repo': json['repo'] == null ? undefined : json['repo'],
        'folder': json['folder'] == null ? undefined : json['folder'],
        'supersededBy': json['superseded_by'] == null ? undefined : json['superseded_by'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function PatchedDocumentToJSON(json: any): PatchedDocument {
    return PatchedDocumentToJSONTyped(json, false);
}

export function PatchedDocumentToJSONTyped(value?: Omit<PatchedDocument, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'title': value['title'],
        'description': value['description'],
        'status': DocumentStatusEnumToJSON(value['status']),
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'production': value['production'],
        'author': value['author'],
        'repo': value['repo'],
        'folder': value['folder'],
        'superseded_by': value['supersededBy'],
        'tags': value['tags'],
    };
}

