/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProductionIncomeCategory
 */
export interface PatchedProductionIncomeCategory {
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProductionIncomeCategory
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    lineCode?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedProductionIncomeCategory
     */
    budget?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProductionIncomeCategory
     */
    notes?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    readonly updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    production?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionIncomeCategory
     */
    incomeCategory?: number | null;
}

/**
 * Check if a given object implements the PatchedProductionIncomeCategory interface.
 */
export function instanceOfPatchedProductionIncomeCategory(value: object): value is PatchedProductionIncomeCategory {
    return true;
}

export function PatchedProductionIncomeCategoryFromJSON(json: any): PatchedProductionIncomeCategory {
    return PatchedProductionIncomeCategoryFromJSONTyped(json, false);
}

export function PatchedProductionIncomeCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProductionIncomeCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'lineCode': json['line_code'] == null ? undefined : json['line_code'],
        'budget': json['budget'] == null ? undefined : json['budget'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'production': json['production'] == null ? undefined : json['production'],
        'incomeCategory': json['income_category'] == null ? undefined : json['income_category'],
    };
}

export function PatchedProductionIncomeCategoryToJSON(json: any): PatchedProductionIncomeCategory {
    return PatchedProductionIncomeCategoryToJSONTyped(json, false);
}

export function PatchedProductionIncomeCategoryToJSONTyped(value?: Omit<PatchedProductionIncomeCategory, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'line_code': value['lineCode'],
        'budget': value['budget'],
        'notes': value['notes'],
        'production': value['production'],
        'income_category': value['incomeCategory'],
    };
}

