/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.96
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyEnum } from './CurrencyEnum';
import {
    CurrencyEnumFromJSON,
    CurrencyEnumFromJSONTyped,
    CurrencyEnumToJSON,
    CurrencyEnumToJSONTyped,
} from './CurrencyEnum';

/**
 * 
 * @export
 * @interface PatchedTicketType
 */
export interface PatchedTicketType {
    /**
     * 
     * @type {number}
     * @memberof PatchedTicketType
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicketType
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicketType
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedTicketType
     */
    readonly archiveAt?: Date | null;
    /**
     * Name of the ticket type, e.g., General Admission, VIP, etc.
     * @type {string}
     * @memberof PatchedTicketType
     */
    externalName?: string;
    /**
     * Internal name for the ticket type, used for system references.
     * @type {string}
     * @memberof PatchedTicketType
     */
    internalName?: string;
    /**
     * Description of the ticket type, if any.
     * @type {string}
     * @memberof PatchedTicketType
     */
    description?: string;
    /**
     * Price of the ticket type.
     * @type {string}
     * @memberof PatchedTicketType
     */
    price?: string;
    /**
     * Currency for the ticket price, e.g. AUD, USD, EUR, etc.
     * 
     * * `AUD` - AUD - Australian Dollar
     * * `CAD` - CAD - Canadian Dollar
     * * `EUR` - EUR - Euro
     * * `GBP` - GBP - British Pound
     * * `JPY` - JPY - Japanese Yen
     * * `NZD` - NZD - New Zealand Dollar
     * * `USD` - USD - United States Dollar
     * @type {CurrencyEnum}
     * @memberof PatchedTicketType
     */
    currency?: CurrencyEnum;
    /**
     * Maximum number of tickets available for this type. null means unlimited. 0 means no tickets available.
     * @type {number}
     * @memberof PatchedTicketType
     */
    limit?: number | null;
    /**
     * Sort order for displaying ticket types, lower numbers appear first.
     * @type {number}
     * @memberof PatchedTicketType
     */
    sortOrder?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicketType
     */
    readonly tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicketType
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedTicketType
     */
    readonly updatedBy?: number | null;
    /**
     * The production venue this ticket type belongs to.
     * @type {number}
     * @memberof PatchedTicketType
     */
    readonly productionVenue?: number;
}



/**
 * Check if a given object implements the PatchedTicketType interface.
 */
export function instanceOfPatchedTicketType(value: object): value is PatchedTicketType {
    return true;
}

export function PatchedTicketTypeFromJSON(json: any): PatchedTicketType {
    return PatchedTicketTypeFromJSONTyped(json, false);
}

export function PatchedTicketTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedTicketType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'externalName': json['external_name'] == null ? undefined : json['external_name'],
        'internalName': json['internal_name'] == null ? undefined : json['internal_name'],
        'description': json['description'] == null ? undefined : json['description'],
        'price': json['price'] == null ? undefined : json['price'],
        'currency': json['currency'] == null ? undefined : CurrencyEnumFromJSON(json['currency']),
        'limit': json['limit'] == null ? undefined : json['limit'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'productionVenue': json['production_venue'] == null ? undefined : json['production_venue'],
    };
}

export function PatchedTicketTypeToJSON(json: any): PatchedTicketType {
    return PatchedTicketTypeToJSONTyped(json, false);
}

export function PatchedTicketTypeToJSONTyped(value?: Omit<PatchedTicketType, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'|'production_venue'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'external_name': value['externalName'],
        'internal_name': value['internalName'],
        'description': value['description'],
        'price': value['price'],
        'currency': CurrencyEnumToJSON(value['currency']),
        'limit': value['limit'],
        'sort_order': value['sortOrder'],
    };
}

