/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Venue } from './Venue';
import {
    VenueFromJSON,
    VenueFromJSONTyped,
    VenueToJSON,
    VenueToJSONTyped,
} from './Venue';
import type { VenueTag } from './VenueTag';
import {
    VenueTagFromJSON,
    VenueTagFromJSONTyped,
    VenueTagToJSON,
    VenueTagToJSONTyped,
} from './VenueTag';

/**
 * 
 * @export
 * @interface PatchedVenueTagAssignment
 */
export interface PatchedVenueTagAssignment {
    /**
     * 
     * @type {number}
     * @memberof PatchedVenueTagAssignment
     */
    readonly id?: number;
    /**
     * 
     * @type {Venue}
     * @memberof PatchedVenueTagAssignment
     */
    venue?: Venue;
    /**
     * 
     * @type {VenueTag}
     * @memberof PatchedVenueTagAssignment
     */
    tag?: VenueTag;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVenueTagAssignment
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVenueTagAssignment
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVenueTagAssignment
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedVenueTagAssignment
     */
    readonly tenantId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedVenueTagAssignment
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedVenueTagAssignment
     */
    updatedBy?: number | null;
}

/**
 * Check if a given object implements the PatchedVenueTagAssignment interface.
 */
export function instanceOfPatchedVenueTagAssignment(value: object): value is PatchedVenueTagAssignment {
    return true;
}

export function PatchedVenueTagAssignmentFromJSON(json: any): PatchedVenueTagAssignment {
    return PatchedVenueTagAssignmentFromJSONTyped(json, false);
}

export function PatchedVenueTagAssignmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedVenueTagAssignment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'venue': json['venue'] == null ? undefined : VenueFromJSON(json['venue']),
        'tag': json['tag'] == null ? undefined : VenueTagFromJSON(json['tag']),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function PatchedVenueTagAssignmentToJSON(json: any): PatchedVenueTagAssignment {
    return PatchedVenueTagAssignmentToJSONTyped(json, false);
}

export function PatchedVenueTagAssignmentToJSONTyped(value?: Omit<PatchedVenueTagAssignment, 'id'|'created_at'|'updated_at'|'tenant_id'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'venue': VenueToJSON(value['venue']),
        'tag': VenueTagToJSON(value['tag']),
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'updated_by': value['updatedBy'],
    };
}

