/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.29
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedWorkLocation
 */
export interface PatchedWorkLocation {
    /**
     * 
     * @type {number}
     * @memberof PatchedWorkLocation
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedWorkLocation
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedWorkLocation
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedWorkLocation
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWorkLocation
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedWorkLocation
     */
    readonly tenantId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedWorkLocation
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWorkLocation
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedWorkLocation
     */
    address?: number;
}

/**
 * Check if a given object implements the PatchedWorkLocation interface.
 */
export function instanceOfPatchedWorkLocation(value: object): value is PatchedWorkLocation {
    return true;
}

export function PatchedWorkLocationFromJSON(json: any): PatchedWorkLocation {
    return PatchedWorkLocationFromJSONTyped(json, false);
}

export function PatchedWorkLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedWorkLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'address': json['address'] == null ? undefined : json['address'],
    };
}

export function PatchedWorkLocationToJSON(json: any): PatchedWorkLocation {
    return PatchedWorkLocationToJSONTyped(json, false);
}

export function PatchedWorkLocationToJSONTyped(value?: Omit<PatchedWorkLocation, 'id'|'created_at'|'updated_at'|'tenant_id'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'updated_by': value['updatedBy'],
        'address': value['address'],
    };
}

