/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedProductionMember
 */
export interface PatchedProductionMember {
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionMember
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionMember
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProductionMember
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    readonly tenantId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    production?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProductionMember
     */
    member?: number;
}

/**
 * Check if a given object implements the PatchedProductionMember interface.
 */
export function instanceOfPatchedProductionMember(value: object): value is PatchedProductionMember {
    return true;
}

export function PatchedProductionMemberFromJSON(json: any): PatchedProductionMember {
    return PatchedProductionMemberFromJSONTyped(json, false);
}

export function PatchedProductionMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProductionMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'production': json['production'] == null ? undefined : json['production'],
        'member': json['member'] == null ? undefined : json['member'],
    };
}

export function PatchedProductionMemberToJSON(json: any): PatchedProductionMember {
    return PatchedProductionMemberToJSONTyped(json, false);
}

export function PatchedProductionMemberToJSONTyped(value?: Omit<PatchedProductionMember, 'id'|'created_at'|'updated_at'|'tenant_id'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'updated_by': value['updatedBy'],
        'production': value['production'],
        'member': value['member'],
    };
}

