/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StatusEnum } from './StatusEnum';
import {
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
    StatusEnumToJSONTyped,
} from './StatusEnum';

/**
 * 
 * @export
 * @interface PatchedProduction
 */
export interface PatchedProduction {
    /**
     * 
     * @type {number}
     * @memberof PatchedProduction
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProduction
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProduction
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProduction
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduction
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduction
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProduction
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedProduction
     */
    endDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedProduction
     */
    venue?: string;
    /**
     * 
     * @type {StatusEnum}
     * @memberof PatchedProduction
     */
    status?: StatusEnum;
    /**
     * 
     * @type {number}
     * @memberof PatchedProduction
     */
    readonly tenantId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedProduction
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProduction
     */
    readonly updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedProduction
     */
    director?: number | null;
}



/**
 * Check if a given object implements the PatchedProduction interface.
 */
export function instanceOfPatchedProduction(value: object): value is PatchedProduction {
    return true;
}

export function PatchedProductionFromJSON(json: any): PatchedProduction {
    return PatchedProductionFromJSONTyped(json, false);
}

export function PatchedProductionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedProduction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'venue': json['venue'] == null ? undefined : json['venue'],
        'status': json['status'] == null ? undefined : StatusEnumFromJSON(json['status']),
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'director': json['director'] == null ? undefined : json['director'],
    };
}

export function PatchedProductionToJSON(json: any): PatchedProduction {
    return PatchedProductionToJSONTyped(json, false);
}

export function PatchedProductionToJSONTyped(value?: Omit<PatchedProduction, 'id'|'created_at'|'updated_at'|'tenant_id'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'description': value['description'],
        'start_date': value['startDate'] === null ? null : ((value['startDate'] as any)?.toISOString()),
        'end_date': value['endDate'] === null ? null : ((value['endDate'] as any)?.toISOString()),
        'venue': value['venue'],
        'status': StatusEnumToJSON(value['status']),
        'director': value['director'],
    };
}

