/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.73
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedVendor
 */
export interface PatchedVendor {
    /**
     * 
     * @type {number}
     * @memberof PatchedVendor
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVendor
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVendor
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedVendor
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    address?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    notes?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    contactName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    contactEmail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    contactPhone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    website?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    abn?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedVendor
     */
    paymentTerms?: string | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedVendor
     */
    tenant?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedVendor
     */
    readonly createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedVendor
     */
    updatedBy?: number | null;
}

/**
 * Check if a given object implements the PatchedVendor interface.
 */
export function instanceOfPatchedVendor(value: object): value is PatchedVendor {
    return true;
}

export function PatchedVendorFromJSON(json: any): PatchedVendor {
    return PatchedVendorFromJSONTyped(json, false);
}

export function PatchedVendorFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedVendor {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'contactName': json['contact_name'] == null ? undefined : json['contact_name'],
        'contactEmail': json['contact_email'] == null ? undefined : json['contact_email'],
        'contactPhone': json['contact_phone'] == null ? undefined : json['contact_phone'],
        'website': json['website'] == null ? undefined : json['website'],
        'abn': json['abn'] == null ? undefined : json['abn'],
        'paymentTerms': json['payment_terms'] == null ? undefined : json['payment_terms'],
        'tenant': json['tenant'] == null ? undefined : json['tenant'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
    };
}

export function PatchedVendorToJSON(json: any): PatchedVendor {
    return PatchedVendorToJSONTyped(json, false);
}

export function PatchedVendorToJSONTyped(value?: Omit<PatchedVendor, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'address': value['address'],
        'notes': value['notes'],
        'contact_name': value['contactName'],
        'contact_email': value['contactEmail'],
        'contact_phone': value['contactPhone'],
        'website': value['website'],
        'abn': value['abn'],
        'payment_terms': value['paymentTerms'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
    };
}

