/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionTypeEnum } from './ActionTypeEnum';
import {
    ActionTypeEnumFromJSON,
    ActionTypeEnumFromJSONTyped,
    ActionTypeEnumToJSON,
    ActionTypeEnumToJSONTyped,
} from './ActionTypeEnum';

/**
 * 
 * @export
 * @interface PatchedAuditLog
 */
export interface PatchedAuditLog {
    /**
     * 
     * @type {number}
     * @memberof PatchedAuditLog
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAuditLog
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAuditLog
     */
    readonly updatedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAuditLog
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAuditLog
     */
    readonly timestamp?: Date;
    /**
     * 
     * @type {ActionTypeEnum}
     * @memberof PatchedAuditLog
     */
    actionType?: ActionTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PatchedAuditLog
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAuditLog
     */
    targetObject?: string;
    /**
     * 
     * @type {any}
     * @memberof PatchedAuditLog
     */
    beforeState?: any | null;
    /**
     * 
     * @type {any}
     * @memberof PatchedAuditLog
     */
    afterState?: any | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedAuditLog
     */
    tenantId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedAuditLog
     */
    createdBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedAuditLog
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof PatchedAuditLog
     */
    user?: number;
}



/**
 * Check if a given object implements the PatchedAuditLog interface.
 */
export function instanceOfPatchedAuditLog(value: object): value is PatchedAuditLog {
    return true;
}

export function PatchedAuditLogFromJSON(json: any): PatchedAuditLog {
    return PatchedAuditLogFromJSONTyped(json, false);
}

export function PatchedAuditLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAuditLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'actionType': json['action_type'] == null ? undefined : ActionTypeEnumFromJSON(json['action_type']),
        'description': json['description'] == null ? undefined : json['description'],
        'targetObject': json['target_object'] == null ? undefined : json['target_object'],
        'beforeState': json['before_state'] == null ? undefined : json['before_state'],
        'afterState': json['after_state'] == null ? undefined : json['after_state'],
        'tenantId': json['tenant_id'] == null ? undefined : json['tenant_id'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'user': json['user'] == null ? undefined : json['user'],
    };
}

export function PatchedAuditLogToJSON(json: any): PatchedAuditLog {
    return PatchedAuditLogToJSONTyped(json, false);
}

export function PatchedAuditLogToJSONTyped(value?: Omit<PatchedAuditLog, 'id'|'created_at'|'updated_at'|'timestamp'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'action_type': ActionTypeEnumToJSON(value['actionType']),
        'description': value['description'],
        'target_object': value['targetObject'],
        'before_state': value['beforeState'],
        'after_state': value['afterState'],
        'tenant_id': value['tenantId'],
        'created_by': value['createdBy'],
        'updated_by': value['updatedBy'],
        'user': value['user'],
    };
}

