/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.111
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProductionStatusEnum } from './ProductionStatusEnum';
import {
    ProductionStatusEnumFromJSON,
    ProductionStatusEnumFromJSONTyped,
    ProductionStatusEnumToJSON,
    ProductionStatusEnumToJSONTyped,
} from './ProductionStatusEnum';

/**
 * 
 * @export
 * @interface Production
 */
export interface Production {
    /**
     * 
     * @type {number}
     * @memberof Production
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Production
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Production
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Production
     */
    readonly archiveAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Production
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Production
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof Production
     */
    startDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Production
     */
    endDate?: Date | null;
    /**
     * 
     * @type {ProductionStatusEnum}
     * @memberof Production
     */
    status?: ProductionStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof Production
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof Production
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Production
     */
    readonly updatedBy: number | null;
    /**
     * The primary venue for the production, not necessarily where all performances will take place.
     * @type {number}
     * @memberof Production
     */
    venue?: number | null;
    /**
     * 
     * @type {number}
     * @memberof Production
     */
    director?: number | null;
}



/**
 * Check if a given object implements the Production interface.
 */
export function instanceOfProduction(value: object): value is Production {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    return true;
}

export function ProductionFromJSON(json: any): Production {
    return ProductionFromJSONTyped(json, false);
}

export function ProductionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Production {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'startDate': json['start_date'] == null ? undefined : (new Date(json['start_date'])),
        'endDate': json['end_date'] == null ? undefined : (new Date(json['end_date'])),
        'status': json['status'] == null ? undefined : ProductionStatusEnumFromJSON(json['status']),
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'venue': json['venue'] == null ? undefined : json['venue'],
        'director': json['director'] == null ? undefined : json['director'],
    };
}

export function ProductionToJSON(json: any): Production {
    return ProductionToJSONTyped(json, false);
}

export function ProductionToJSONTyped(value?: Omit<Production, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'start_date': value['startDate'] === null ? null : ((value['startDate'] as any)?.toISOString()),
        'end_date': value['endDate'] === null ? null : ((value['endDate'] as any)?.toISOString()),
        'status': ProductionStatusEnumToJSON(value['status']),
        'venue': value['venue'],
        'director': value['director'],
    };
}

