/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.103
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionVenue
 */
export interface ProductionVenue {
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ProductionVenue
     */
    readonly venueName: string;
    /**
     * 
     * @type {Date}
     * @memberof ProductionVenue
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductionVenue
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductionVenue
     */
    readonly archiveAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    readonly updatedBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    production: number;
    /**
     * 
     * @type {number}
     * @memberof ProductionVenue
     */
    venue: number;
}

/**
 * Check if a given object implements the ProductionVenue interface.
 */
export function instanceOfProductionVenue(value: object): value is ProductionVenue {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('venueName' in value) || value['venueName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('production' in value) || value['production'] === undefined) return false;
    if (!('venue' in value) || value['venue'] === undefined) return false;
    return true;
}

export function ProductionVenueFromJSON(json: any): ProductionVenue {
    return ProductionVenueFromJSONTyped(json, false);
}

export function ProductionVenueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionVenue {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'venueName': json['venue_name'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'production': json['production'],
        'venue': json['venue'],
    };
}

export function ProductionVenueToJSON(json: any): ProductionVenue {
    return ProductionVenueToJSONTyped(json, false);
}

export function ProductionVenueToJSONTyped(value?: Omit<ProductionVenue, 'id'|'venue_name'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'production': value['production'],
        'venue': value['venue'],
    };
}

