/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.98
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductionCostCategory
 */
export interface ProductionCostCategory {
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof ProductionCostCategory
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductionCostCategory
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof ProductionCostCategory
     */
    readonly archiveAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof ProductionCostCategory
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionCostCategory
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductionCostCategory
     */
    lineCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductionCostCategory
     */
    budget: string;
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    readonly updatedBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    production: number;
    /**
     * 
     * @type {number}
     * @memberof ProductionCostCategory
     */
    companyCostCategory?: number | null;
}

/**
 * Check if a given object implements the ProductionCostCategory interface.
 */
export function instanceOfProductionCostCategory(value: object): value is ProductionCostCategory {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('budget' in value) || value['budget'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    if (!('production' in value) || value['production'] === undefined) return false;
    return true;
}

export function ProductionCostCategoryFromJSON(json: any): ProductionCostCategory {
    return ProductionCostCategoryFromJSONTyped(json, false);
}

export function ProductionCostCategoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductionCostCategory {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'name': json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'lineCode': json['line_code'] == null ? undefined : json['line_code'],
        'budget': json['budget'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
        'production': json['production'],
        'companyCostCategory': json['company_cost_category'] == null ? undefined : json['company_cost_category'],
    };
}

export function ProductionCostCategoryToJSON(json: any): ProductionCostCategory {
    return ProductionCostCategoryToJSONTyped(json, false);
}

export function ProductionCostCategoryToJSONTyped(value?: Omit<ProductionCostCategory, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
        'line_code': value['lineCode'],
        'budget': value['budget'],
        'production': value['production'],
        'company_cost_category': value['companyCostCategory'],
    };
}

