/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.98
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShortTextConfig
 */
export interface ShortTextConfig {
    /**
     * Maximum length of the text
     * @type {number}
     * @memberof ShortTextConfig
     */
    maxLength?: number;
    /**
     * Minimum length of the text
     * @type {number}
     * @memberof ShortTextConfig
     */
    minLength?: number;
    /**
     * Number of lines for the text input
     * @type {number}
     * @memberof ShortTextConfig
     */
    lines?: number;
    /**
     * 
     * @type {string}
     * @memberof ShortTextConfig
     */
    pattern?: string | null;
}

/**
 * Check if a given object implements the ShortTextConfig interface.
 */
export function instanceOfShortTextConfig(value: object): value is ShortTextConfig {
    return true;
}

export function ShortTextConfigFromJSON(json: any): ShortTextConfig {
    return ShortTextConfigFromJSONTyped(json, false);
}

export function ShortTextConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShortTextConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'maxLength': json['max_length'] == null ? undefined : json['max_length'],
        'minLength': json['min_length'] == null ? undefined : json['min_length'],
        'lines': json['lines'] == null ? undefined : json['lines'],
        'pattern': json['pattern'] == null ? undefined : json['pattern'],
    };
}

export function ShortTextConfigToJSON(json: any): ShortTextConfig {
    return ShortTextConfigToJSONTyped(json, false);
}

export function ShortTextConfigToJSONTyped(value?: ShortTextConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'max_length': value['maxLength'],
        'min_length': value['minLength'],
        'lines': value['lines'],
        'pattern': value['pattern'],
    };
}

