/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.22
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `planning` - Planning
 * * `auditions` - Auditions Open
 * * `rehearsals` - Rehearsals
 * * `tech` - Tech Week
 * * `performances` - Performance Run
 * * `completed` - Completed
 * * `cancelled` - Cancelled
 * * `archived` - Archived
 * @export
 */
export const StatusEnum = {
    Planning: 'planning',
    Auditions: 'auditions',
    Rehearsals: 'rehearsals',
    Tech: 'tech',
    Performances: 'performances',
    Completed: 'completed',
    Cancelled: 'cancelled',
    Archived: 'archived'
} as const;
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];


export function instanceOfStatusEnum(value: any): boolean {
    for (const key in StatusEnum) {
        if (Object.prototype.hasOwnProperty.call(StatusEnum, key)) {
            if (StatusEnum[key as keyof typeof StatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function StatusEnumFromJSON(json: any): StatusEnum {
    return StatusEnumFromJSONTyped(json, false);
}

export function StatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusEnum {
    return json as StatusEnum;
}

export function StatusEnumToJSON(value?: StatusEnum | null): any {
    return value as any;
}

export function StatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): StatusEnum {
    return value as StatusEnum;
}

