/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.40
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface State
 */
export interface State {
    /**
     * 
     * @type {number}
     * @memberof State
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof State
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof State
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof State
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof State
     */
    name: string;
    /**
     * Abbreviation or code for the state/region
     * @type {string}
     * @memberof State
     */
    code?: string;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    tenant: number;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof State
     */
    country: number;
}

/**
 * Check if a given object implements the State interface.
 */
export function instanceOfState(value: object): value is State {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('country' in value) || value['country'] === undefined) return false;
    return true;
}

export function StateFromJSON(json: any): State {
    return StateFromJSONTyped(json, false);
}

export function StateFromJSONTyped(json: any, ignoreDiscriminator: boolean): State {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'],
        'code': json['code'] == null ? undefined : json['code'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'country': json['country'],
    };
}

export function StateToJSON(json: any): State {
    return StateToJSONTyped(json, false);
}

export function StateToJSONTyped(value?: Omit<State, 'id'|'created_at'|'updated_at'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'code': value['code'],
        'tenant': value['tenant'],
        'updated_by': value['updatedBy'],
        'country': value['country'],
    };
}

