/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.107
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tag
 */
export interface Tag {
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof Tag
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Tag
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Tag
     */
    readonly archiveAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    name: string;
    /**
     * Hex colour code without the # symbol
     * @type {string}
     * @memberof Tag
     */
    colour?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Tag
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    readonly tenant: number;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof Tag
     */
    readonly updatedBy: number | null;
}

/**
 * Check if a given object implements the Tag interface.
 */
export function instanceOfTag(value: object): value is Tag {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archiveAt' in value) || value['archiveAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenant' in value) || value['tenant'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('updatedBy' in value) || value['updatedBy'] === undefined) return false;
    return true;
}

export function TagFromJSON(json: any): Tag {
    return TagFromJSONTyped(json, false);
}

export function TagFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tag {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': (json['archive_at'] == null ? null : new Date(json['archive_at'])),
        'name': json['name'],
        'colour': json['colour'] == null ? undefined : json['colour'],
        'description': json['description'] == null ? undefined : json['description'],
        'tenant': json['tenant'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'],
    };
}

export function TagToJSON(json: any): Tag {
    return TagToJSONTyped(json, false);
}

export function TagToJSONTyped(value?: Omit<Tag, 'id'|'created_at'|'updated_at'|'archive_at'|'tenant'|'created_by'|'updated_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'colour': value['colour'],
        'description': value['description'],
    };
}

