/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.100
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimeConfig
 */
export interface TimeConfig {
    /**
     * 
     * @type {string}
     * @memberof TimeConfig
     */
    minTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimeConfig
     */
    maxTime?: string | null;
}

/**
 * Check if a given object implements the TimeConfig interface.
 */
export function instanceOfTimeConfig(value: object): value is TimeConfig {
    return true;
}

export function TimeConfigFromJSON(json: any): TimeConfig {
    return TimeConfigFromJSONTyped(json, false);
}

export function TimeConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimeConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'minTime': json['min_time'] == null ? undefined : json['min_time'],
        'maxTime': json['max_time'] == null ? undefined : json['max_time'],
    };
}

export function TimeConfigToJSON(json: any): TimeConfig {
    return TimeConfigToJSONTyped(json, false);
}

export function TimeConfigToJSONTyped(value?: TimeConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_time': value['minTime'],
        'max_time': value['maxTime'],
    };
}

