/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.101
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TimePickerConfiguration
 */
export interface TimePickerConfiguration {
    /**
     * 
     * @type {string}
     * @memberof TimePickerConfiguration
     */
    minTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TimePickerConfiguration
     */
    maxTime?: string | null;
}

/**
 * Check if a given object implements the TimePickerConfiguration interface.
 */
export function instanceOfTimePickerConfiguration(value: object): value is TimePickerConfiguration {
    return true;
}

export function TimePickerConfigurationFromJSON(json: any): TimePickerConfiguration {
    return TimePickerConfigurationFromJSONTyped(json, false);
}

export function TimePickerConfigurationFromJSONTyped(json: any, ignoreDiscriminator: boolean): TimePickerConfiguration {
    if (json == null) {
        return json;
    }
    return {
        
        'minTime': json['min_time'] == null ? undefined : json['min_time'],
        'maxTime': json['max_time'] == null ? undefined : json['max_time'],
    };
}

export function TimePickerConfigurationToJSON(json: any): TimePickerConfiguration {
    return TimePickerConfigurationToJSONTyped(json, false);
}

export function TimePickerConfigurationToJSONTyped(value?: TimePickerConfiguration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'min_time': value['minTime'],
        'max_time': value['maxTime'],
    };
}

