/* tslint:disable */
/* eslint-disable */
/**
 * Limelight API
 * Limelight manages your theatre production process from auditions to bump out.
 *
 * The version of the OpenAPI document: 1.0.30
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorkLocation
 */
export interface WorkLocation {
    /**
     * 
     * @type {number}
     * @memberof WorkLocation
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof WorkLocation
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkLocation
     */
    readonly updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkLocation
     */
    archiveAt?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof WorkLocation
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof WorkLocation
     */
    readonly tenantId: number;
    /**
     * 
     * @type {number}
     * @memberof WorkLocation
     */
    readonly createdBy: number | null;
    /**
     * 
     * @type {number}
     * @memberof WorkLocation
     */
    updatedBy?: number | null;
    /**
     * 
     * @type {number}
     * @memberof WorkLocation
     */
    address: number;
}

/**
 * Check if a given object implements the WorkLocation interface.
 */
export function instanceOfWorkLocation(value: object): value is WorkLocation {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function WorkLocationFromJSON(json: any): WorkLocation {
    return WorkLocationFromJSONTyped(json, false);
}

export function WorkLocationFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkLocation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'archiveAt': json['archive_at'] == null ? undefined : (new Date(json['archive_at'])),
        'name': json['name'],
        'tenantId': json['tenant_id'],
        'createdBy': json['created_by'],
        'updatedBy': json['updated_by'] == null ? undefined : json['updated_by'],
        'address': json['address'],
    };
}

export function WorkLocationToJSON(json: any): WorkLocation {
    return WorkLocationToJSONTyped(json, false);
}

export function WorkLocationToJSONTyped(value?: Omit<WorkLocation, 'id'|'created_at'|'updated_at'|'tenant_id'|'created_by'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_at': value['archiveAt'] === null ? null : ((value['archiveAt'] as any)?.toISOString()),
        'name': value['name'],
        'updated_by': value['updatedBy'],
        'address': value['address'],
    };
}

